### PR TITLE
Replace CLIP with ByT5

### PR DESCRIPTION
**Pull request by freth251**
Replaces CLIPTokenizer and FlaxCLIPTextModel, with ByT5Tokenizer and FlaxT5EncoderModel respectively.

### CODE REVIEW

**Comment by contrebande-labs** [comment]
Hi Thanks for this! I will look into it tomorrow. Did you test it?

**Review by contrebande-labs — APPROVED** [review]

**Comment by contrebande-labs** [comment]
I merged it now, but I will test it tomorrow. If you did some testing on your side, please let me know about it. Thanks!

**Comment by freth251** [comment]
I have not done any testing. From what I understand, we test it by running a training loop. Is that right?

**Comment by contrebande-labs** [comment]
Yes, we can test one iteration of the training loop. Do you have a GPU on your workstation? If not, maybe we can wait until we have access to the TPU VM. I don't see any warnings in the IDE (VS Code). In any case, I will try to test it tomorrow. I have a RTX 1070 so I'll see if there we I can test it on it. I'm also thinkin about writing some unit tests for individual functions... I will be preparing the dataset next so we can run it on something...

**Pull request merged**
